# Generated by Django 5.2.5 on 2025-08-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='challenges',
            field=models.TextField(blank=True, help_text='Description of challenges faced', verbose_name='Challenges'),
        ),
        migrations.AddField(
            model_name='project',
            name='key_features',
            field=models.TextField(blank=True, help_text='JSON array of key features', verbose_name='Key Features'),
        ),
        migrations.AddField(
            model_name='project',
            name='results',
            field=models.TextField(blank=True, help_text='Project outcomes and impact', verbose_name='Results & Impact'),
        ),
        migrations.AddField(
            model_name='project',
            name='solutions',
            field=models.TextField(blank=True, help_text='How challenges were solved', verbose_name='Solutions'),
        ),
    ]
