# Generated by Django 5.2.5 on 2025-08-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0002_project_challenges_project_key_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='reading_time',
            field=models.PositiveIntegerField(default=0, help_text='Estimated reading time in minutes', verbose_name='Reading Time (minutes)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug'),
        ),
    ]
