# Generated by Django 5.2.5 on 2025-08-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0003_blogpost_reading_time_alter_blogpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='delivery_time',
            field=models.CharField(blank=True, help_text="e.g., '2-4 weeks'", max_length=50, verbose_name='Delivery Time'),
        ),
        migrations.AddField(
            model_name='service',
            name='features',
            field=models.TextField(blank=True, help_text='JSON array of key features', verbose_name='Key Features'),
        ),
        migrations.AddField(
            model_name='service',
            name='process_steps',
            field=models.TextField(blank=True, help_text='JSON array of process steps', verbose_name='Process Steps'),
        ),
    ]
