# Generated by Django 5.2.5 on 2025-08-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0004_service_delivery_time_service_features_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonials'},
        ),
        migrations.AddField(
            model_name='testimonial',
            name='date_given',
            field=models.DateField(blank=True, help_text='When the testimonial was provided', null=True, verbose_name='Date Given'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which testimonial appears (lower = first)', verbose_name='Display Order'),
        ),
    ]
