# Generated by Django 5.2.5 on 2025-08-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorPalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Palette Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('light_primary', models.CharField(default='#6366f1', max_length=7, verbose_name='Light Primary Color')),
                ('light_secondary', models.CharField(default='#8b5cf6', max_length=7, verbose_name='Light Secondary Color')),
                ('light_accent', models.CharField(default='#06b6d4', max_length=7, verbose_name='Light Accent Color')),
                ('light_background', models.CharField(default='#f8fafc', max_length=7, verbose_name='Light Background Color')),
                ('light_text', models.CharField(default='#1e293b', max_length=7, verbose_name='Light Text Color')),
                ('dark_primary', models.CharField(default='#818cf8', max_length=7, verbose_name='Dark Primary Color')),
                ('dark_secondary', models.CharField(default='#a78bfa', max_length=7, verbose_name='Dark Secondary Color')),
                ('dark_accent', models.CharField(default='#67e8f9', max_length=7, verbose_name='Dark Accent Color')),
                ('dark_background', models.CharField(default='#0f172a', max_length=7, verbose_name='Dark Background Color')),
                ('dark_text', models.CharField(default='#f1f5f9', max_length=7, verbose_name='Dark Text Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Color Palette',
                'verbose_name_plural': 'Color Palettes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NavigationMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Menu Title')),
                ('url', models.CharField(max_length=200, verbose_name='URL')),
                ('icon', models.CharField(blank=True, help_text='Bootstrap or Font Awesome icon class', max_length=50, verbose_name='Icon Class')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_external', models.BooleanField(default=False, verbose_name='Is External Link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Navigation Menu Item',
                'verbose_name_plural': 'Navigation Menu Items',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Portfolio', max_length=100, verbose_name='Site Name')),
                ('site_tagline', models.CharField(blank=True, max_length=200, verbose_name='Site Tagline')),
                ('site_description', models.TextField(blank=True, verbose_name='Site Description')),
                ('site_url', models.URLField(blank=True, verbose_name='Site URL')),
                ('active_theme', models.CharField(choices=[('electric_neon', 'Electric Neon (Tech-Forward)'), ('sunset_gradient', 'Sunset Gradient (Creative)'), ('ocean_deep', 'Ocean Deep (Professional)'), ('forest_modern', 'Forest Modern (Eco-Friendly)')], default='electric_neon', max_length=20, verbose_name='Active Theme')),
                ('default_mode', models.CharField(choices=[('light', 'Light Mode'), ('dark', 'Dark Mode'), ('auto', 'Auto (System Preference)')], default='auto', max_length=10, verbose_name='Default Mode')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Contact Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Location')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Meta Keywords')),
                ('google_analytics_id', models.CharField(blank=True, max_length=20, verbose_name='Google Analytics ID')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('enable_blog', models.BooleanField(default=True, verbose_name='Enable Blog')),
                ('enable_testimonials', models.BooleanField(default=True, verbose_name='Enable Testimonials')),
                ('enable_contact_form', models.BooleanField(default=True, verbose_name='Enable Contact Form')),
                ('enable_animations', models.BooleanField(default=True, verbose_name='Enable Animations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Parameter',
                'verbose_name_plural': 'Site Parameters',
            },
        ),
    ]
