# Generated by Django 5.2.5 on 2025-08-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('category', models.CharField(choices=[('general', 'General'), ('services', 'Services'), ('process', 'Process'), ('pricing', 'Pricing'), ('technical', 'Technical'), ('contact', 'Contact')], default='general', max_length=20, verbose_name='Category')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_featured', models.BooleanField(default=False, help_text='Show in main FAQ section', verbose_name='Is Featured')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['category', 'order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='FontPalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Palette Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('heading_font', models.CharField(help_text='CSS font-family for headings', max_length=200, verbose_name='Heading Font')),
                ('body_font', models.CharField(help_text='CSS font-family for body text', max_length=200, verbose_name='Body Font')),
                ('accent_font', models.CharField(blank=True, help_text='CSS font-family for accents/special elements', max_length=200, verbose_name='Accent Font')),
                ('heading_weight', models.CharField(default='700', max_length=10, verbose_name='Heading Font Weight')),
                ('body_weight', models.CharField(default='400', max_length=10, verbose_name='Body Font Weight')),
                ('base_font_size', models.CharField(default='16px', max_length=10, verbose_name='Base Font Size')),
                ('google_fonts_url', models.URLField(blank=True, help_text='URL to import Google Fonts', verbose_name='Google Fonts URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Font Palette',
                'verbose_name_plural': 'Font Palettes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title/Position')),
                ('company', models.CharField(max_length=200, verbose_name='Company/Institution')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Location')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if current position', null=True, verbose_name='End Date')),
                ('is_current', models.BooleanField(default=False, verbose_name='Is Current Position')),
                ('description', models.TextField(verbose_name='Description')),
                ('achievements', models.TextField(blank=True, help_text='Bullet points of achievements', verbose_name='Key Achievements')),
                ('technologies', models.TextField(blank=True, help_text='Comma-separated list of technologies', verbose_name='Technologies Used')),
                ('entry_type', models.CharField(choices=[('work', 'Work Experience'), ('education', 'Education'), ('certification', 'Certification'), ('achievement', 'Achievement'), ('project', 'Major Project')], default='work', max_length=20, verbose_name='Entry Type')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured experience section', verbose_name='Is Featured')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Professional Journey Entry',
                'verbose_name_plural': 'Professional Journey Entries',
                'ordering': ['-start_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuickAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Question')),
                ('answer', models.TextField(max_length=500, verbose_name='Answer')),
                ('icon', models.CharField(blank=True, help_text='Bootstrap icon class (e.g., bi-clock)', max_length=50, verbose_name='Icon Class')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quick Answer',
                'verbose_name_plural': 'Quick Answers',
                'ordering': ['order', 'question'],
            },
        ),
        migrations.AddField(
            model_name='siteparameter',
            name='about_me_text',
            field=models.TextField(blank=True, help_text='Main about section content', verbose_name='About Me Text'),
        ),
        migrations.AddField(
            model_name='siteparameter',
            name='active_font_palette',
            field=models.CharField(choices=[('modern_professional', 'Modern Professional'), ('creative_editorial', 'Creative Editorial'), ('tech_minimalist', 'Tech Minimalist'), ('warm_humanist', 'Warm Humanist')], default='modern_professional', max_length=20, verbose_name='Active Font Palette'),
        ),
        migrations.AddField(
            model_name='siteparameter',
            name='availability_message',
            field=models.TextField(blank=True, help_text='Custom message about availability', verbose_name='Availability Message'),
        ),
        migrations.AddField(
            model_name='siteparameter',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available for Projects'), ('busy', 'Currently Busy'), ('unavailable', 'Not Available')], default='available', max_length=20, verbose_name='Availability Status'),
        ),
        migrations.AddField(
            model_name='siteparameter',
            name='bio',
            field=models.TextField(blank=True, help_text='Short biography', verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='siteparameter',
            name='fun_facts',
            field=models.JSONField(blank=True, default=dict, help_text="Store as JSON: {'cups_of_coffee': 500, 'projects_completed': 50, ...}", verbose_name='Fun Facts'),
        ),
        migrations.AddField(
            model_name='siteparameter',
            name='my_story_text',
            field=models.TextField(blank=True, help_text='Personal/professional story content', verbose_name='My Story Text'),
        ),
        migrations.AddField(
            model_name='siteparameter',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Owner Full Name'),
        ),
        migrations.AddField(
            model_name='siteparameter',
            name='owner_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Professional Title'),
        ),
        migrations.AddField(
            model_name='siteparameter',
            name='profile_image_base64',
            field=models.TextField(blank=True, verbose_name='Profile Image (Base64)'),
        ),
        migrations.AddField(
            model_name='siteparameter',
            name='response_time',
            field=models.CharField(default='Usually within 24 hours', max_length=50, verbose_name='Response Time'),
        ),
        migrations.AddField(
            model_name='siteparameter',
            name='values_interests',
            field=models.JSONField(blank=True, default=dict, help_text="Store as JSON: {'values': [...], 'interests': [...]}", verbose_name='Values & Interests'),
        ),
    ]
