# Generated by Django 5.2.5 on 2025-08-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0002_faq_fontpalette_professionaljourney_quickanswer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteparameter',
            name='base_font_size',
            field=models.CharField(default='16px', help_text='Base font size for body text (e.g., 16px, 1rem)', max_length=10, verbose_name='Base Font Size'),
        ),
        migrations.AddField(
            model_name='siteparameter',
            name='heading_font_scale',
            field=models.FloatField(default=1.25, help_text='Scale factor for heading sizes (1.0 = no scaling, 1.25 = 25% larger)', verbose_name='Heading Font Scale'),
        ),
        migrations.AddField(
            model_name='siteparameter',
            name='small_font_scale',
            field=models.FloatField(default=0.875, help_text='Scale factor for small text (0.875 = 12.5% smaller)', verbose_name='Small Font Scale'),
        ),
    ]
