# Generated by Django 5.2.5 on 2025-08-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0003_siteparameter_base_font_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteparameter',
            name='skills_expertise',
            field=models.JSONField(blank=True, default=list, help_text="Store as JSON: [{'name': 'Python', 'category': 'programming', 'level': 90, 'icon': 'code', 'color': 'primary'}]", verbose_name='Skills & Expertise'),
        ),
    ]
